### ISSUE TITLE
PA Review: Feature 1 - Making Posts

### ISSUE THREAD

**Issue by sam-mcclure** [sam-mcclure/rollover#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by eshoule** [comment]
Looks great! Are the different types of posts supposed to be styled differently once they are posted? The text, quote, chat all look the same. Also please address the following items

- [ ] Photo preview for the image post squishes to photo (once it's posted its fine).
- [ ] When I post an audio file, it does not show up on the feed. There is a post but nothing in it.
- [ ] I get a POST 500 level error when I try to make a video post.

**Comment by sam-mcclure** [comment]
Hey Liz, I fixed these 3 action items. Thanks!

**Comment by eshoule** [comment]
Awesome! The audio and video files seem to take a couple of seconds to post, so it would be cool to have some sort of loading thing or to disable the button once you press it so people don't click post multiple times b/c they think it's not posting. Good job!
